- hosts: work_machines
  become: true

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
    - name: Store current username
      command: whoami
      register: whoami
      become: no
    - set_fact:
        username: "{{ whoami.stdout_lines[0] }}"
    - debug: var=username

  roles:
    - role: ericsysmin.docker.docker
    - role: packages
    - role: ansible
    - role: oh_my_zsh
    - role: dotfiles
      become: no
    - role: doom_emacs
    - role: fonts
    - role: asdf
    - role: fzf
      become: no