- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
    - name: include vars
      include_vars:
        file: variables.yml

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/oh_my_zsh.yml
    - include: tasks/check_docker_installation.yml
    - include: tasks/docker.yml
      when: docker_installed is failed
    - include: tasks/doom_emacs.yml
    - include: tasks/fonts.yml
