- hosts: work_machines
  become: true
  roles:
    - role: gantsign.antigen
      users:
        - username: diomedet
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: agnoster
          antigen_bundles:
            # Bundles from the default repo (robbyrussell's oh-my-zsh).
            - name: git
            - name: pip
            - name: command-not-found
            # Syntax highlighting bundle.
            - name: zsh-syntax-highlighting 
              url: zsh-users/zsh-syntax-highlighting
    - role: ericsysmin.docker.docker

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
    - name: Store current username
      command: whoami
      register: whoami
      become: no
    - set_fact:
        username: "{{ whoami.stdout_lines[0] }}"
    - debug: var=username

  tasks:
    - include: tasks/users.yml
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
      become: no
    - include: tasks/doom_emacs.yml
    - include: tasks/fonts.yml
      become: no
    - include: tasks/asdf.yml
      become: no
    - include: tasks/fzf.yml
      become: no
