- name: Install zsh packages
  apt:
    name: 
      - zsh
      - curl
  become: yes

- name: Return to the current user
  command: whoami
  become: no

- name: Check if oh my zsh is installed
  command: "[ -d ~/.oh-my-zsh ]"
  register: oh_my_zsh_installed
  ignore_errors: True

- name: Install oh my zsh 
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: oh_my_zsh_installed is failed

- name: Change shell to the given user
  user:
    name: "{{ username }}"
    shell: /bin/zsh
