- name: Install zsh packages
  apt:
    name: 
      - zsh
      - curl
  become: yes

- name: Return to the current user
  command: whoami
  become: yes
  become_user: "{{ username }}"

- name: Check if oh my zsh is installed
  command: "cd ~/.oh-my-zsh"
  register: oh_my_zsh_installed
  ignore_errors: true
  become: yes
  become_user: "{{ username }}"

- name: Install oh my zsh 
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: oh_my_zsh_installed is failed
  become: yes
  become_user: "{{ username }}"

- name: Change shell to the given user
  user:
    name: "{{ username }}"
    shell: /bin/zsh
  become: yes
  become_user: "{{ username }}"
