- name: Install packages
  become: yes
  apt: 
    name:
      - vim
      - htop
      - snapd
      - tmux
      - zsh
      - peek
      - obs-studio
      - cmake
      - libssl-dev
      - zlib1g-dev
      - vlc

- name: Install snaps
  snap:
    name:
      - yubioath-desktop
      - code
      - insomnia
      - discord
      - telegram-desktop
      - spotify

- name: Install snaps classic
  snap:
    classic: true
    name:
      - slack
      - code
      - alacritty
