- name: Install packages
  become: yes
  apt: 
    name:
      - vim
      - htop
      - snapd
      - tmux
      - zsh
      - alacritty
      - peek
      - slack-desktop
      - telegram-desktop
      - obs-studio
      - cmake
      - libssl-dev
      - zlib1g-dev
      - vlc
      - spotify-client
- name: Install snaps
  snap:
    name:
      - yubioath-desktop
      - code
      - insomnia
      - discord
